name: Refresh weather data

on: 
  push:
    branches:
      - main
  schedule:
    - cron: '0 22 * * *' # 6:00 AM Beijing time is 22:00 UTC

jobs:
  refresh-data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Run data download script
        run: python download_data.py
